DECLARE @ClientSiteKeys TABLE
(
	[ClientSiteId] [int],
	[KeyNo] [varchar](15),
	[Description] [varchar](512)
)

insert into @ClientSiteKeys values (390, 'MC-1033', 'Resi: Penny & Joe Di Santo - 7 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1034', 'Resi: Tim & Sarah Lincoln - 4 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1035', 'Resi: David William & Angela Mitchell - 9 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1036', 'Resi: David & Milica Cowie - 14 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1037', 'Resi: Jenny Conti - 1 Sharpley Ave')
insert into @ClientSiteKeys values (390, 'MC-1039', 'Resi: Francis Bartholomew Taranto - 32 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1041', 'Resi: George Walter & Anne Hines - 31 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1042', 'Resi: Bernard & Samantha Klimecki - 138 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1043', 'Resi: Carmel Simonelli - 12 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1045', 'Resi: Peter & Jane Wrench - 4 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1046', 'Resi: John Hepworth & Sally-Anne Swift - 11 Sharpley Ave (101)')
insert into @ClientSiteKeys values (390, 'MC-1047', 'Resi: Joe Ciccone - 73 Spinnaker Tce (Th 5)')
insert into @ClientSiteKeys values (390, 'MC-1048', 'Resi: Chris & Marie Kalogirou - 3 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1051', 'Resi: Wayne & Trudie Lorraine Fox - 2 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1052', 'Resi: Sacha French - 26 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1053', 'Resi: Vincenzo & Julie Cannatelli - 11 Sharpley Ave (204)')
insert into @ClientSiteKeys values (390, 'MC-1054', 'Resi: Robert & Sarah Fishwick - 30 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1055A', 'Resi: &rew & Diane Mackey - 83 Spinnaker Tce (C 201)')
insert into @ClientSiteKeys values (390, 'MC-1055B', 'Resi: Jatech Pty Ltd - 83 Spinnaker Tce (C 202)')
insert into @ClientSiteKeys values (390, 'MC-1057', 'Resi: Gary De Gier - 83 Spinnaker Tce (B 205)')
insert into @ClientSiteKeys values (390, 'MC-1058', 'Resi: Scott & Karen Wightwick - 3 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1059', 'Resi: Ian Paterson - 5 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1061', 'Resi: Trevor Nurse & Kim Nurse - 27 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1062', 'Resi: Rosemary Ann Martin - 12 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1063', 'Resi: Jennifer Conti & Heath S&ow - 4 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1064', 'Resi: Phillip John & Joy Ashfield - 11 Sharpley Ave (107)')
insert into @ClientSiteKeys values (390, 'MC-1065', 'Resi: Noel & Sharon Griffiths - 18 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1066', 'Resi: Ian & Marisa Angelico - 15 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1067', 'Resi: Rodney Keith & Heidi Williams - 2 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1068', 'Resi: Greg & Brooke Lee - 4 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1069', 'Resi: Keith & Margaret Lord - 41 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1070', 'Resi: Gary Noel & Lynette Joy Wright - 1 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1071', 'Resi: Melissa & Sam Colosimo - 26 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1072', 'Resi: Matt Kopp - 81 Spinnaker Tce (Th 1)')
insert into @ClientSiteKeys values (390, 'MC-1073', 'Resi: Dorothy May Pill - 16 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1074', 'Resi: Colin Thomas & Margo Murphy - 83 Spinnaker Tce (C 204)')
insert into @ClientSiteKeys values (390, 'MC-1075', 'Resi: Katherine Louise Tilley - 6 Mainsail Place')
insert into @ClientSiteKeys values (390, 'MC-1076', 'Resi: Kevin & Vonda Donnellan - 14 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1077', 'Resi: Graeme & Bette Pearson - 4 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1078', 'Resi: Timothy Charles & Evelyn Forsyth - 32 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1079', 'Resi: Marine P/L Patrick & Rosetta Galle - 83 Spinnaker Tce (B 104)')
insert into @ClientSiteKeys values (390, 'MC-1080', 'Resi: Graham John & Karyn Lee Hodge - 69 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1081', 'Resi: Helen Larinda Burns - 34 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1082', 'Resi: Wendy Lundgaard & Vincent Conserva - 8 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1084', 'Resi: Anita & Timothy Alan Kleeberg - 83 Spinnaker Tce (A 206)')
insert into @ClientSiteKeys values (390, 'MC-1085', 'Resi: Roberto Martin & Marta Susana Eppel - 142 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1086', 'Resi: Lukas Desmond & Kerry Ann Planke - 62 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1087', 'Resi: Joan Wyatt - 55 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1088', 'Resi: Michael & Diana Dezilwa - 8 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1089', 'Resi: Phillip & Wendy Simmons - 10 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1090', 'Resi: Ross & Kerryanne Fearne - 22 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1091', 'Resi: Susan Carol Dowdle - 53 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1092', 'Resi: Arthur Ozdil - 44 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1093', 'Resi: Michael Unali - 6 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1094', 'Resi: David & Beverley Paterson - 15 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1095', 'Resi: Helen Rhonda French - 40 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1096', 'Resi: Frank & Gayle Carew - 83 Spinnaker Tce (B 102)')
insert into @ClientSiteKeys values (390, 'MC-1098', 'Resi: Clifford Douglas & Janette Farrow - 24 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1099', 'Resi: Moammar Alshimirti & Hind Marhoon - 3 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1100', 'Resi: Kerry Thomson - 6 Cordage Close')
insert into @ClientSiteKeys values (390, 'MC-1101', 'Resi: Kerry Griffin & Ilsa Macraild - 140 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1102', 'Resi: Stefan & Angela Therese Schmitzer - 6 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1103', 'Resi: Michael & Susan Kelly - 158 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1105', 'Resi: Sophie Louise Hemburrow - 19 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1106', 'Resi: Warren John & Lisa Nicole Jordan - 52 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1107', 'Resi: John David & Dorothy Edith Howard - 71 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1108', 'Resi: Milton Bernard & Betty Davenport - 26 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1110', 'Resi: Tony Stamatopoulos & Sharon Mason - 3 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1111', 'Resi: Grazyna Maria Lambert - 45 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1112', 'Resi: David & Marika Pearson - 68 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1115', 'Resi: Abbot Kelly James - 1 Binnacle Crt')
insert into @ClientSiteKeys values (390, 'MC-1116', 'Resi: Donato & Robyn Lesley Di Divirgilio - 45 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1117', 'Resi: Peter & Sue Kemp - 11 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1118', 'Resi: Nick Adam Deed & Fiona Elizabeth Deed - 9 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1119', 'Resi: Melissa & Wasyl Rosati - 83 Spinnaker Tce (C 103)')
insert into @ClientSiteKeys values (390, 'MC-1120', 'Resi: Brydie Lee &erson - 1 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1121', 'Resi: Gary Frederick Seedsman - 26 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1122', 'Resi: Eric David & Rosemary Garrett - 10 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1124', 'Resi: Micheal & Gillian Maclagan - 33 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1125', 'Resi: Dilika Perera - 83 Spinnaker Tce (A 107)')
insert into @ClientSiteKeys values (390, 'MC-1127', 'Resi: Jacqueline Ann Lofts - 60 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1128', 'Resi: Brian & Diana Treloar - 2 Windward Lane')
insert into @ClientSiteKeys values (390, 'MC-1129', 'Resi: Phillip & Bernadette Walker - 83 Spinnaker Tce (A 207)')
insert into @ClientSiteKeys values (390, 'MC-1133', 'Resi: Antonios & Jenny Violentis - 7 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1135', 'Resi: Garry & Deborah Ringwood - - 83 Spinnaker Tce (B 101)')
insert into @ClientSiteKeys values (390, 'MC-1141', 'Resi: Keith Enoch & Catherine Horobin - 42 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1142', 'Resi: Warren Prebble & Nina Zutelia - 19 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1145', 'Resi: Wayne Douglas & S&ra Kay Edis - 11 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1147', 'Resi: Jane & Tony Heseltine - 32 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1148', 'Resi: Kris Lee & Cheryl Miller - 15 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1150', 'Resi: Gavan & Cristina Stewart - 11 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1154', 'Resi: Neil Robert & Jennifer Christine Daniels - 14 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1155', 'Resi: Neil Albert & Lynette Ethel Glendenning - 89 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1157', 'Resi: Marianna Reaperrace - 3 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1158', 'Resi: Nick & Mary Soccio - 9 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1159', 'Resi: Leo Liddell & Kay Helen Wilson - 54 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1160', 'Resi: Darren Murray & Melinda Balfour - 91 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1167', 'Resi: Kenneth John & Cynthia Burns - 25 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1170', 'Resi: Ryan Wilson & Claire Wytcherley (AirBnB) - 66a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1172', 'Resi: Marilyn Alexis Yates - 27 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1175', 'Resi: Evan Maxwell & Rose Crane - 38 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1176', 'Resi: Tony & Rosanna Venuto - 29 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1178', 'Resi: Tony & Sofie Tartaglia - 64 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1179A', 'Resi: Brenton & Louise Crabb - 7 Sharpley Ave')
insert into @ClientSiteKeys values (390, 'MC-1179B', 'Resi: Darren Moyle & Bettrcia Powley - 35 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1180', 'Resi: Mario Lawrence & Marlene Vella-West - 40 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1182', 'Resi: Melisa & Wasyl Rosati - 83 Spinnaker Tce (C 203)')
insert into @ClientSiteKeys values (390, 'MC-1184', 'Resi: Nillab Joshan - 66 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1185', 'Resi: Anthony & Laura Longo - 36 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1186', 'Resi: Richard Anthony Ward Allberry - 6 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1187', 'Resi: Deborah Scott - 8 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1189', 'Resi: Anthony Philip Woolcock - 5 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1190', 'Resi: Melissa Ann Bell - 68 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1193', 'Resi: Trevor & Kim O`Connell - 48 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1197', 'Resi: Angela Marie Burgman - 6 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1198', 'Resi: Gary Iacovou - 16 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1199', 'Resi: Scott Marshal Farley - 56 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1200', 'Resi: Henriucs Wihelmus & Aida Hendriks - 39 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1201', 'Resi: Ross Damien & Jules Ann Alex&er - 3 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1202', 'Resi: James Christopher & Shirit Adams - 26 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1203', 'Resi: &rew Flett & Lorraine Denise Lang - 12 Mariners Way')
insert into @ClientSiteKeys values (390, 'MC-1204', 'Resi: &rew Iredale & Lisa Karen Iredale - 16 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1205', 'Resi: Terry Graham & Pamela May Pearce - 61 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1206', 'Resi: Graham Sprigg & Pamela Macalister - 9 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1207', 'Resi: Michael Vawdrey - 16 Brindabella Point')
insert into @ClientSiteKeys values (390, 'MC-1208', 'Resi: John Patrick & Lynette Dorothy O`Brien - 40 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1209', 'Resi: Wendy Kollias - 20 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1211', 'Resi: Jennifer Louise Fallon - 14 Brindabella Point')
insert into @ClientSiteKeys values (390, 'MC-1212', 'Resi: Natalie Kim Collins - 34 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1214', 'Resi: Beverley Baron - 22 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1215', 'Resi: Michael Allan & Rebecca Alice Lofts - 52 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1216', 'Resi: David & Jenny Ferguson - 1 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1217', 'Resi: Steve & Debbie Casper - 17 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1219', 'Resi: Joshua & Katrina Wharton - 54 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1220', 'Resi: &rei La Greca & Lisa Holden - 83 Spinnaker Tce (A 203)')
insert into @ClientSiteKeys values (390, 'MC-1221', 'Resi: John & Lucy Brancatisano - 12 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1222', 'Resi: Mark &rew Thompson - 14 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1223', 'Resi: Bill Papavasiliou - 57 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1224', 'Resi: Karen Gobel - 44 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1225', 'Resi: Jeffrey Graham & Barbara Joyce Flather - 12 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1226', 'Resi: Rosalia Bernadette Turgarelli - 11 Sharpley Ave (104)')
insert into @ClientSiteKeys values (390, 'MC-1227', 'Resi: William & Judith Watson - 51 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1228', 'Resi: Arcangela Inserra - 12 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1229', 'Resi: Craig James & Debra Lee Skipper - 19 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1230', 'Resi: Sebastian Campisi & Lucia Cetrola (AirBnB) - 8 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1231', 'Resi: Michael & Meni Rozakis - 34 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1232', 'Resi: Amy & Stuart Bennett - 6 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1233', 'Resi: Victoria Stewart & Gina Marion Sherwood - 46 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1235', 'Resi: Daniel & Andrea Livingston - 27 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1237', 'Resi: Kevin Henry Webster - 35 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1238', 'Resi: Judy S&ra Farrer - 6 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1239', 'Resi: Suzanne Carol Kemp - 83 Spinnaker Tce (A 104)')
insert into @ClientSiteKeys values (390, 'MC-1240', 'Resi: Grant & Liz Chipperfield - 5 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1241', 'Resi: Justine Elise Quayle & &rew Brian Quayle - 5 Cordage Close')
insert into @ClientSiteKeys values (390, 'MC-1242', 'Resi: Krishanthi Dissanayate & Marcus Jenkins - 2 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1243', 'Resi: Mary Clarke - 4 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1244', 'Resi: David Gardener & Michelle Causon - 73 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1245', 'Resi: Johnathan & Jacqueline Kha - 1 Jackstay Close')
insert into @ClientSiteKeys values (390, 'MC-1246', 'Resi: Damien Michael Ritchie - 34a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1247', 'Resi: Sharon Leanne Petterson - 39 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1248', 'Resi: Mark & Paul Davies - 6 Binnacle Crt')
insert into @ClientSiteKeys values (390, 'MC-1249', 'Resi: Nick & Rina Gabrielle Lettieri - 83 Spinnaker Tce B203')
insert into @ClientSiteKeys values (390, 'MC-1250', 'Resi: Bernice Mary Glen - 154 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1251', 'Resi: Rosemary Clark - 5 Charter Place')
insert into @ClientSiteKeys values (390, 'MC-1252', 'Resi: Carl Gadini & Grace Renon - 30 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1254', 'Resi: Vicki Anne St&ing - 4 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1255', 'Resi: Mark & Elizabeth Casley - 156 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1257', 'Resi: Susanne Louise Haworth - 54 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1258', 'Resi: Graham &rew Makey - 42 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1259', 'Resi: Nicholas Michael Kumar - 6 Jackstay Close')
insert into @ClientSiteKeys values (390, 'MC-1260', 'Resi: John William Attrill - 2 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1261', 'Resi: Kathleen Ross & Howard Stokes - 1 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1262', 'Resi: Lisa Young - 3 Binnacle Crt')
insert into @ClientSiteKeys values (390, 'MC-1263', 'Resi: Robert Watt & Renee Temby - 17 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1264', 'Resi: John Barbopoulos & Danielle Lee Savage - 64 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1265', 'Resi: Susan Moore - 32a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1266', 'Resi: Patrick Cangia & Chantel Cangia - 11 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1267', 'Resi: Michael Hilton & Michelle O''connor - 22 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1268', 'Resi: Shannon Riches - 6 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1269', 'Resi: Graeme Hamilton & Anna Maria Murn - 29 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1270', 'Resi: Adam John Dyer - 2 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1271', 'Resi: Julie Moody & Danielle Crooks - 2 Jackstay Close')
insert into @ClientSiteKeys values (390, 'MC-1272', 'Resi: Nick & Diane Catherine Gizas - 12 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1273', 'Resi: Marie-Lyne Dunez - 70 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1274', 'Resi: Niels Roderick & Kim Valerie Campbell - 29 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1275', 'Resi: Ryan Robert Arnold Gaffney - 40 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1276', 'Resi: John William & Ann Matheson - 11 Sharpley Ave (202)')
insert into @ClientSiteKeys values (390, 'MC-1277', 'Resi: Deborah Kuhl & Tony Mcmillan -Tenants - 36 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1278', 'Resi: Mauro Guido & Margaret Joan Perez - 30 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1279', 'Resi: Peter Hollins & Elizabeth Reed - 37 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1280', 'Resi: Zivko Steve & Sarah Marlo Kastrati - 9 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1281', 'Resi: Glenn Bragge & Kristine Berntsen - 9 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1282', 'Resi: James William Harington - 10 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1283', 'Resi: Nora Iiknur Tabak - 41 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1285', 'Resi: Patricia Katia Pearce & Andrew Charles Pearce - 7 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1286', 'Resi: John Robert Gordon - 2 Castaway St')
insert into @ClientSiteKeys values (390, 'MC-1287', 'Resi: Sharon Anne Cook - 44 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1288', 'Resi: Mark Robert Portbury - 16 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1289', 'Resi: John & Maureen O''sullivan - 26 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1290', 'Resi: Terry Phillip Mottrom & Deidre Ann Mottrom - 88 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1291', 'Resi: Corrina Woollard - 172 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1292', 'Resi: Rachel Am&a Beight - 60a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1293', 'Resi: Shane & Janine O`Sullivan - 2 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1294', 'Resi: Brenton Emanuel & Louise Varigos - 16 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1295', 'Resi: Michael Rumbald Pake & Roberta Marie Pake - 43 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1296', 'Resi: David Varney & Joan Forence Botterill - 43 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1297', 'Resi: Jodi & &rew Brookes - 10 Mariners Way')
insert into @ClientSiteKeys values (390, 'MC-1298', 'Resi: Barry John & Joy Maree Linton - 14 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1299', 'Resi: Ross & Judi Hallam - 21 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1300', 'Resi: Damian Patrick & Nancy Galle - 78 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1301', 'Resi: Steve Tankey - 50 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1302', 'Resi: Ben Thomas Skruzny & Sarah Marino - 162 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1304', 'Resi: Cindy Maria Reukers - 3 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1306', 'Resi: Adriano & Angelica De Luca Unit Trust - 9 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1307', 'Resi: Janine Louise O''sullivan - 25 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1308', 'Resi: Stuart James Cox - 1 Bowline Lane')
insert into @ClientSiteKeys values (390, 'MC-1309', 'Resi: Brian Cameron & Judith Kathleen Niven - 50 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1310', 'Resi: John Laurence & Lynette Joy Garone - 44 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1311', 'Resi: Kiersten Sawyer & Murray Mcneill - 46 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1312', 'Resi: Douglas Alex&er & Rosalie Joy Mcgregor - 52 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1313', 'Resi: S&y Joan St Leger - 28 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1314', 'Resi: Edwin Rudolf & Elisa Elizabeth Kiesel - 42 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1315', 'Resi: Irene Joan Francis & James Kingsley - 38 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1316', 'Resi: Joas De Dues & Lillia Kuim-In Lay - 86 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1317', 'Resi: Garry Paul & Melinda Sue Mitchell - 4 Bowline Lane')
insert into @ClientSiteKeys values (390, 'MC-1318', 'Resi: Ted & Kim Smirnoff - 48 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1319', 'Resi: George Dimitriou Milonas - 75 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1320', 'Resi: Tanya Elizabeth Scagliarini - 1 Staysail Lane')
insert into @ClientSiteKeys values (390, 'MC-1321', 'Resi: John Francis & Catherine Ann Gallivan - 53 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1322', 'Resi: Steve & Caroline Gustin Lena Pollock - 38 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1323', 'Resi: Rory & Karen Maree Thompson - 72 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1324', 'Resi: Bernie & Mary Antonietta Conforti - 40 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1325', 'Resi: Danielle Cuttler - 32 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1326', 'Resi: Vaughan Curtis Sullivan-Sinfield - 34 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1327', 'Resi: Linda Loader - 57 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1328', 'Resi: Malcolm Gregor & Janet Knight - 34 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1329', 'Resi: Con & Effie Glavas - 67 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1330', 'Resi: John Ernest & Linnea Sue Donnelly - 8 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1331', 'Resi: Bernard John Carroll - 59 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1332', 'Resi: Nicole Maree Hahn & Jonathon Matthew Migill - 69 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1333', 'Resi: Arnica Community Care P/L - 77 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1334', 'Resi: Mar&a Anthony & Justin Irons - 2 Bowline Lane')
insert into @ClientSiteKeys values (390, 'MC-1335', 'Resi: Julie Diane Hoffman Green - 30 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1336', 'Resi: Suzanne Leigh Jones & Norimen Francisse - 65 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1337', 'Resi: Jonathon Philip & Jennifer Kay Slingsby - 6 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1338', 'Resi: Stephen Matthew & Frances Thompson - 10 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1339', 'Resi: David & Sue Jackson - 7 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1340', 'Resi: Mary Elizabeth Kelly - 26 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1341', 'Resi: Am&a Sue Mercuri - 4 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1342', 'Resi: Lorraine Sorboe Rushton - 55 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1343', 'Resi: Ian John & Julie Cugley - 14 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1344', 'Resi: Ian Ronald & Helen Joy Davis - 6 Windward Lane')
insert into @ClientSiteKeys values (390, 'MC-1345', 'Resi: Nick & Mary Lazarevski - 3 Sharpley Ave')
insert into @ClientSiteKeys values (390, 'MC-1346', 'Resi: Bruce Rodney Mansfield - 8 Windward Lane')
insert into @ClientSiteKeys values (390, 'MC-1347', 'Resi: Daniel James Patch & Belinda Shapardon - 3 Staysail Lane')
insert into @ClientSiteKeys values (390, 'MC-1348', 'Resi: Peter & Julie Horibin - 30 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1349', 'Resi: Gordon & Margaret Hall - 5 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1350', 'Resi: Peter Geoffrey & Karen Marie Kon - 47 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1351', 'Resi: Ray & Kerrie Lightbody - 67 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1352', 'Resi: George & Pamela Byford - 16 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1353', 'Resi: Vern Corrie & Janette Louise Ferguson - 5 Windward Lane')
insert into @ClientSiteKeys values (390, 'MC-1354', 'Resi: Patrick Rampal & Judith Anne Williams - 62 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1355', 'Resi: Allison Jane Fisher - 71 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1356', 'Resi: Effi & John Houridis - 7 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1357', 'Resi: Richard Peter Eccles - 4 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1360', 'Resi: Stephen Sharp & Susan Halcenko (AirBnB) - 16 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1364', 'Resi: Michael Bailey & Joan Kimberley - 6 Admiralty Crt')
insert into @ClientSiteKeys values (390, 'MC-1365', 'Resi: &rew & Holley Oppy - 7 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1366', 'Resi: Tan & Sahara Taylor - 25 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1367', 'Resi: Carin & Wayne Wood - 7 Windward Lane')
insert into @ClientSiteKeys values (390, 'MC-1368', 'Resi: Johnathon Leach Watson - 4 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1369', 'Resi: Simon Cayzer & Debbie Mercer - 24 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1370', 'Resi: Roy Douglas & Janice Pamela Aldrich - 14 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1371', 'Resi: Toby John Benjamin - 20 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1372', 'Resi: Guilia Tassone - 39 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1373', 'Resi: Manuel Francis & Janine Kay Hill - 10 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1374', 'Resi: Rob & Loretta Lois Rosa ) - 166 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1375', 'Resi: Paul Smith & Kerry Lorraine O`Byrne - 51 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1376', 'Resi: Rohan Graeme Cook - 12 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1377', 'Resi: Liam &rew & Patricia Carol Mcglashan - 19 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1379', 'Resi: David James & Lorraine Joy White - 18 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1380', 'Resi: Christopher Anthony & Bronwen Hocking - 73 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1381', 'Resi: Richard John & Bonnie Victoria Carrington - 64 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1382', 'Resi: Louis - 61 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1384', 'Resi: Colin & Fiona Hyde - 20 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1385', 'Resi: &rew Thomas & Susan Scott Purnell - 31 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1386', 'Resi: Am&a Jane & Gary Hardeman - 59 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1387', 'Resi: Steve Edward Boyle & Elizabeth Ann Boyle - 23 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1388', 'Resi: Elaine Heather Young - 41 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1389', 'Resi: Angela & Rodney Dean - - 38 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1390', 'Resi: Ian Colin Mulhauser & Wendie Hopkins - 20 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1391', 'Resi: Robert James Kennedy & Sue Kennedy - 3 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1392', 'Resi: Gail Elizabeth Moore - 15 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1393', 'Resi: Graeme & Narelle Lynne Lear - 83 Spinnaker Tce - C 104')
insert into @ClientSiteKeys values (390, 'MC-1394', 'Resi: Monique & Thomas Ian Johnstone - 82 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1395', 'Resi: Paul Robert & Faye Paul Chase - 64 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1396', 'Resi: Fiona Holl& - 11 Sharpley (201)')
insert into @ClientSiteKeys values (390, 'MC-1397', 'Resi: David Lee Mcpadden & Bridget Ann Mccarthy - 88 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1398', 'Resi: Matthew James & Christine Ellen Harrington - 47 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1400', 'Resi: Jim Gooden - 4 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1401', 'Resi: Rea & Belinda Cowie - 53 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1402', 'Resi: Paul & Tanya Fong (Tenants ) - 16 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1403', 'Resi: Stephen Southwood - 4 Mariners Way')
insert into @ClientSiteKeys values (390, 'MC-1404', 'Resi: Warrick Graeme & Deborah Pearson - 8 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1405', 'Resi: Boris & Maria Carmelina Bozinovski - 83 Spinnaker Tce (A106)')
insert into @ClientSiteKeys values (390, 'MC-1406', 'Resi: Tim & Julie Ann Pepperell - 23 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1407', 'Resi: Graham Ernest & Katrina May Wickenden - 12 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1408', 'Resi: Maureen Elizabeth Ramsay Ballantine - 75 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1409', 'Resi: Joseph Anthony & Teresa Gerace - 57 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1410', 'Resi: &rew James & Julie Maree Mc''queen - 25 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1411', 'Resi: Christopher Kevin Kalenco & Alida Storaci - 1 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1412', 'Resi: Michael - 164 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1413', 'Resi: Darren O''sullivan - 28 Castaway St')
insert into @ClientSiteKeys values (390, 'MC-1414', 'Resi: Salvatore & Angela Maria Cavarra - 27 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1415', 'Resi: Bill & Vanessa Patterson - 29 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1416', 'Resi: Davider Singh & Sam&eep Kaur (AirBnB) - 104 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1417', 'Resi: Joy & Warren Ball - 17 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1420', 'Resi: Pascale Raymond Turvey - 63 Spinnaker Tce (Th 10)')
insert into @ClientSiteKeys values (390, 'MC-1421', 'Resi: Robert & Aurawan Grey - 17 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1422', 'Resi: Harry & Trudy Ziegerink - 12 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1423', 'Resi: Carlos Marcelo & Belinda Hern&ez - 80 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1424', 'Resi: Desley Margaret Wallis - 30 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1425', 'Resi: Lorraine Margaret Barnett - 35 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1426', 'Resi: Anthony Duse - 42 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1427', 'Resi: Holiday Rental (AirBnB) Jason Laird - 28 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1428', 'Resi: Bhali&er & Marina Gurm - 24 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1429', 'Resi: Michael Raymond & Corrine Ann Holmes - 10 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1430', 'Resi: Shaun Mcvicar - 21 Evans St')
insert into @ClientSiteKeys values (390, 'MC-1431', 'Resi: Vincenzo & Nella Sciacca - 22 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1432', 'Resi: Frank David & Rosetta Palermo - 33 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1433', 'Resi: Tony & Julie Ciantar - 19 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1434', 'Resi: Jane Elizabeth & Ashley Cole - 27 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1435', 'Resi: Frank & Sally Patricia &rew - 33 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1436', 'Resi: Aydin & Gulsen Tat - 1 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1437', 'Resi: Dirk & Deborah De Haan - 19 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1438', 'Resi: Barry & Anna Sheppard - 8 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1439', 'Resi: Joshua Leanardo & Barbarah Zarco - 5 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1440', 'Resi: Tim William & Else Josefine O''halloran - 24 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1441', 'Resi: Detlev & Brenda Geiger - 39 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1442', 'Resi: Susan Phyllis Smith & Ian Bruce Smith - 43 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1443', 'Resi: Rodney Donald Wright - 52a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1444', 'Resi: David Robinson & Gail Robinson - 4 Cordage Close')
insert into @ClientSiteKeys values (390, 'MC-1445', 'Resi: Ashleigh Brooke Fleming - 1 Mizzen Place')
insert into @ClientSiteKeys values (390, 'MC-1446', 'Resi: Elizabeth Deryan - 7 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1447', 'Resi: Thai Nguyen (Primary) - 150 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1448', 'Resi: Darrin Prichard & Elisha Crew - 8 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1449', 'Resi: Shancon Pty Ltd - 46 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1450', 'Resi: Ferris Alfifi - 22 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1451', 'Resi: Byron Arthur & Margret Ann Hill - 29 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1452', 'Resi: Trent Moon - 30 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1453', 'Resi: Anthony & Belinda Lo Casto - 13 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1454', 'Resi: Erin Danielle Lacy & Craig Mcmanamny (AirBnB) - 5 Binnacle Crt')
insert into @ClientSiteKeys values (390, 'MC-1455', 'Resi: Roger &rew Simpson - 14 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1456', 'Resi: Joshua &rew Peter Green & Ebony May Hill - 21 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1457', 'Resi: Frederik Isarin - 4 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1459', 'Resi: Christian Marc & Shani Davinia Vetter - 22 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1460', 'Resi: Sarah Catherine Bromley - 20 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1461', 'Resi: Brian & Carolyn Cronin - 32 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1462', 'Resi: G&el Martha Cove P/L - Ian G&el - 12 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1463', 'Resi: Megan Grace Lott & Gregory Paul Mccann - 37 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1464', 'Resi: John & Reena Anna Moraes - 28 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1465', 'Resi: Theo & Anna Maria Rozakis - 52 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1466', 'Resi: Ms Jillian Annette Hedin - 83 Spinnaker Tce (A101)')
insert into @ClientSiteKeys values (390, 'MC-1467', 'Resi: Benjamin Paul Nutbean - 18 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1468', 'Resi: Scott Matthew Smith & Somporn Smith - 10 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1469', 'Resi: Lynne Luxford - 44a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1471', 'Resi: Ewan Campbell & Maitena Zantvoort - 18 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1472', 'Resi: Massimiliano & Martha Lucia Catenacci - 25 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1473', 'Resi: Prudence Stewart Plovanic - 18 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1474', 'Resi: Julie Marie Bos - 7 Wheelhouse Mews')
insert into @ClientSiteKeys values (390, 'MC-1475', 'Resi: Paul Desmond & Suzanne Hamill - 9 Wheelhouse Mews')
insert into @ClientSiteKeys values (390, 'MC-1476', 'Resi: S&ro Franco Di Disante - 10 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1477', 'Resi: Kelly Lee Gooden - 6 Outrigger Place')
insert into @ClientSiteKeys values (390, 'MC-1478', 'Resi: David Arundale - 36 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1479', 'Resi: Mark Robert Portbury - 3 Wheelhouse Mews')
insert into @ClientSiteKeys values (390, 'MC-1480', 'Resi: Joel William &erson - 4 Outrigger Place')
insert into @ClientSiteKeys values (390, 'MC-1481', 'Resi: Tony & Elizabeth Manevski - 10 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1482', 'Resi: Scott Graeme & Phang Pimlott - 24 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1483', 'Resi: &rea & Barry Crouch - 72 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1484', 'Resi: Lynton & Wendy Patrcia Barriball - 20 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1485', 'Resi: Matthew & Shannon Palmer - 7 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1486', 'Resi: Mark Cooke & Catherine Fennell - 21 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1487', 'Resi: Michael & Alison Jane Janssens - 21 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1488', 'Resi: Mark & Christine Rowe - 5 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1489', 'Resi: Barry Boxall - 76a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1490', 'Resi: Paul Anthony & Daniela Angela Hannan - 11 Sharpley (203)')
insert into @ClientSiteKeys values (390, 'MC-1491', 'Resi: Gail & David Patrick Cremen - 24 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1492', 'Resi: Peter & Noelene Phillips - 4 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1493', 'Resi: Gary Dennis & Nanette Helena Taylor - 36 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1494', 'Resi: Phillip Joseph Fitzpatrick - 62 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1495', 'Resi: Jonathon Anthony Gerace - 1 Wheelhouse Mews')
insert into @ClientSiteKeys values (390, 'MC-1496', 'Resi: Mathew Pistillo & Lara Rita Basso - 9 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1497', 'Resi: Lesley Kell Von Braun - 16 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1498', 'Resi: Denise Julia Cremasco - 12 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1499', 'Resi: Raymond George Ward & Joy Marie Ward - 15 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1500', 'Resi: Ann Elizabeth Cerche - 54 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1501', 'Resi: Anthony Michael Dodson - 28 Sovereign Point')
insert into @ClientSiteKeys values (390, 'MC-1502', 'Resi: Jerry William & Leone S&ra Howard - 24 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1503', 'Resi: Stephen Richard & S&ra Leanne Bain - 12 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1504', 'Resi: Giovanni & John Villante - 20 Seaspray Close')
insert into @ClientSiteKeys values (390, 'MC-1506', 'Resi: Deborah Sharon & William John Mckay - 22 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1507', 'Resi: Simone Connell & Brett Webb - 11 Wheelhouse Mews')
insert into @ClientSiteKeys values (390, 'MC-1508', 'Resi: Lira Stratus - 22 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1509', 'Resi: Roula Aroyro Tsiolas - 50 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1510', 'Resi: Samantha Cass & Scott Traynor - 38 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1511', 'Resi: David & Wendy Kathleen Kosenko - 85 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1512', 'Resi: Stacey & Braden Graham - 65 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1513', 'Resi: Warren Paul & Eleanor Bull - 10 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1514', 'Resi: Marcis Kurzeme - 16 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1515', 'Resi: John & Carol Ann Rodgers - 38a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1516', 'Resi: Daine Michael Taylor & Emily Rose Vanston - 21 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1517', 'Resi: Chris & Patrica Lee Hill - 74 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1518', 'Resi: Luke John Conway & Chloe Elise Jayne Baker - 36 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1519', 'Resi: Lori Wilson - 5 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1521', 'Resi: John & Tina Belanti - 58 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1522', 'Resi: &rew & Mary Cavaggion - 4 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1523', 'Resi: Trent  Malconson & Rebecca Orlando (AirBnB) - 74a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1524', 'Resi: Kristen Rosine Mcfarlane - 14 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1525', 'Resi: Anthony Albert & Ursula Brigid Rushton - 26 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1526', 'Resi: Christpher Charles & Louise Wetheridge - 5 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1527', 'Resi: Ronald James Batrouney - 32 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1528', 'Resi: Martyn Baker - 23 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1529', 'Resi: Dino Gaetano & Donna Marie Gulzia - 11 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1530', 'Resi: Kimberley Jade P/L ATF JK Future Trust - 78 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1533', 'Resi: Marg Mosbey & Neil Williams - 7 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1534', 'Resi: Kathleen Louise Rogers - 41 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1535', 'Resi: Antonio & Filomena Carollo - 7 Brindabella Point')
insert into @ClientSiteKeys values (390, 'MC-1536', 'Resi: Nicholas Stuart & Jane Josephine Metlikovec - 1 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1537', 'Resi: Michael John & Loris Jean Wilton - 136 Clipper Quay')
insert into @ClientSiteKeys values (390, 'MC-1538', 'Resi: Chris Jonchev - 5 Jackstay Close')
insert into @ClientSiteKeys values (390, 'MC-1539', 'Resi: Mo Han Du & Uanessa Lui - 27 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1540', 'Resi: Michelle & Paul - 56 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1541', 'Resi: Roy & Diane Ashcroft - 1 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1542', 'Resi: Scott Bradshaw & Elizabeth Howard - 34 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1543', 'Resi: Michelle & Chris Adams - 35 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1544', 'Resi: Catherine Dunshea - 6 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1545', 'Resi: Mitchell Gregory & Richelle Lee Mcclell& - 8 Seahaven Way')
insert into @ClientSiteKeys values (390, 'MC-1546', 'Resi: Lynda Maree Micic & Mark Micic - 15 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1547', 'Resi: Nicholas Zamias & Maria Verkios - 6 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1548', 'Resi: Karen Johns - 32 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1549', 'Resi: Michelle & William Morris - 61 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1550', 'Resi: Bruce Musgrove & Judith Musgrove - 13 Portside Way')
insert into @ClientSiteKeys values (390, 'MC-1551', 'Resi: Ngai Fung Mak & Yun Li - 62a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1552', 'Resi: Kerry Michelle Sheehan - 68a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1553', 'Resi: Craig Richard Anketell - 6 Whipstaff Lane')
insert into @ClientSiteKeys values (390, 'MC-1554', 'Resi: Michael & Ludmila Cunningham - 79 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1555', 'Resi: Peter & Denise Margaret Ward - 50 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1556', 'Resi: Peter & Robyn Darby - 83 Spinnaker Tce (A202)')
insert into @ClientSiteKeys values (390, 'MC-1558', 'Resi: Bentley Vercoe & Taegen Kerley - 30 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1559', 'Resi: Neil Bakker & Georgia Smyrk - 76 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1561', 'Resi: Noah Burnside - 3 Cringle Place')
insert into @ClientSiteKeys values (390, 'MC-1563', 'Resi: Paul Robert Fleming & Danielle Wall - 21 The Cove')
insert into @ClientSiteKeys values (390, 'MC-1564', 'Resi: Victoria Rowe & Doug Rowe - 15 Brindabella Point')
insert into @ClientSiteKeys values (390, 'MC-1565', 'Resi: Ryan Xain-Loong & Jade Foo - 68 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1566', 'Resi: Janine Dunlop Daddo - 2 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1567', 'Resi: Elodie Patricia Martin - 16 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1568', 'Resi: Punam - 14 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1571', 'Resi: Sean Sinclair & Maree Therese Davies - 54a Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1572', 'Resi: Fred & Susan Ann Wardan - 30 Castaway St')
insert into @ClientSiteKeys values (390, 'MC-1573', 'Resi: Elizabeth Ann Gittus & Jeffrey Ian - 27 South Harbour Esp')
insert into @ClientSiteKeys values (390, 'MC-1574', 'Resi: Lindsay Wayne King & Vicki Lynne King - 31 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1575', 'Resi: &rew Kimpton & Theresa Kimpton-Forde - 10 Castaway St')
insert into @ClientSiteKeys values (390, 'MC-1576', 'Resi: Maxwell James & Angela Mary Coen - 21 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1577', 'Resi: Simone Borthwick - 7 Narrows Crt')
insert into @ClientSiteKeys values (390, 'MC-1582', 'Resi: Tony Hart - 83 Spinnaker Tce (B204)')
insert into @ClientSiteKeys values (390, 'MC-1583', 'Resi: Dianne - 6 Blue Moon Rise')
insert into @ClientSiteKeys values (390, 'MC-1584', 'Resi: Miriam Lowles - 22 Anchorage Ave')
insert into @ClientSiteKeys values (390, 'MC-1585', 'Resi: Jolt - 18 Deck Tce')
insert into @ClientSiteKeys values (390, 'MC-1586', 'Resi: &rew Tartaglia & Jacqueline Ibrahim - 12 Ragamuffin Point')
insert into @ClientSiteKeys values (390, 'MC-1587', 'Resi: Stacey & Brian Menzies - 17 Spinnaker Tce')
insert into @ClientSiteKeys values (390, 'MC-1588', 'Resi: Brett Antony & Nola Leigh Jones - 13 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1589', 'Resi: Jianfeng Su - 17 Helsal Point')
insert into @ClientSiteKeys values (390, 'MC-1590', 'Resi: Hans Georg & Jennifer Anke Brinkies - 63 Oceanic Drive')
insert into @ClientSiteKeys values (390, 'MC-1591', 'Resi: Cheryl & Joel Mason - 3 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1592', 'Resi: Paul & Elizabeth Lila Marchetti - 1 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1593', 'Resi: Jan Gilman & Catherine Neil - 24 Harbourside Esp')
insert into @ClientSiteKeys values (390, 'MC-1594', 'Resi: Chiara Anna Gorman - 34 Helm Ave')
insert into @ClientSiteKeys values (390, 'MC-1596', 'Resi: Sam & Deb Garden - 15 Anchorage Way')
insert into @ClientSiteKeys values (390, 'MC-1597', 'Resi: Stephen Shane & Lynne Rodoreda - 9 Anchorage Way')

insert into ClientSiteKeys
select t.ClientSiteId, t.KeyNo, t.[Description]
from @ClientSiteKeys t
left join ClientSiteKeys k
on t.KeyNo = k.KeyNo
where k.Id is null