USE [CityWatchDb]
GO

/****** Object:  Table [dbo].[LoginUserHistory]    Script Date: 05-05-2025 15:46:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LoginUserRCHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LoginTime] [datetime] NULL,
	[IPAddress] [nvarchar](50) NULL,
	[GuardId] [int] NULL,
 CONSTRAINT [PK_LoginUserRCHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


