USE [CityWatchDb]
GO

/****** Object:  Table [dbo].[KpiSendTimesheetClientSites]    Script Date: 18-08-2025 12:37:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KpiSendKVClientSites](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KVScheduleId] [int] NOT NULL,
	[ClientSiteId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


