

CREATE TABLE [dbo].[HrSettingsClientTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HrSettingsId] [int] NOT NULL,
	[ClientTypeId] [int] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HrSettingsClientTypes]  WITH CHECK ADD FOREIGN KEY([ClientTypeId])
REFERENCES [dbo].[ClientTypes] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[HrSettingsClientTypes]  WITH CHECK ADD FOREIGN KEY([HrSettingsId])
REFERENCES [dbo].[HrSettings] ([Id])
ON DELETE CASCADE
GO


