
/****** Object:  Index [IX_GuardLogs_TagScanHitLogRefId]    Script Date: 05-05-2026 07:16:40 PM ******/
CREATE NONCLUSTERED INDEX [IX_GuardLogs_TagScanHitLogRefId] ON [dbo].[GuardLogs]
(
	[TagScanHitLogRefId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


