CREATE TABLE [dbo].[ClientSiteLogBooks]
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES ClientSites(Id) ON DELETE CASCADE,
	[Type] INT NOT NULL,
	[Date] Date NOT NULL,
	IsClosed BIT NOT NULL DEFAULT 0
)


CREATE TABLE dbo.Guards
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(75) UNIQUE,
	SecurityNo VARCHAR(50) UNIQUE,
	Initial varchar(10) UNIQUE
)

CREATE TABLE [dbo].[GuardLogs]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ClientSiteLogBookId] INT NOT NULL FOREIGN KEY REFERENCES [ClientSiteLogBooks](Id) ON DELETE CASCADE,
	[EventDateTime] DATETIME NOT NULL,
	[Notes] VARCHAR(2048) NOT NULL,
	[GuardId] INT NOT NULL FOREIGN KEY REFERENCES [Guards](Id) ON DELETE CASCADE,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE,
)