CREATE TABLE GuardLogins
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GuardId INT NOT NULL FOREIGN KEY REFERENCES Guards(Id),
	LoginDate DATE NOT NULL,
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES ClientSites(Id),
	SmartWandId INT NULL FOREIGN KEY REFERENCES ClientSiteSmartWands(Id),
	PositionId INT NULL FOREIGN KEY REFERENCES IncidentReportPositions(Id),
	OnDuty DATETIME NOT NULL,
	OffDuty DATETIME NOT NULL,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [Users](Id) ON DELETE CASCADE,
	CONSTRAINT UQ_GuardLogin UNIQUE(GuardId, LoginDate, ClientSiteId)
)
