DROP TABLE GuardLogins
GO

CREATE TABLE dbo.GuardLogins
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	LoginDate DATETIME NOT NULL,
	GuardId INT NOT NULL FOREIGN KEY REFERENCES Guards(Id),
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id),	
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES ClientSites(Id),
	ClientSiteLogBookId INT NOT NULL FOREIGN KEY REFERENCES ClientSiteLogBooks (Id),
	SmartWandId INT NULL FOREIGN KEY REFERENCES ClientSiteSmartWands(Id),
	PositionId INT NULL FOREIGN KEY REFERENCES IncidentReportPositions(Id),
	OnDuty DATETIME NOT NULL,
	OffDuty DATETIME NOT NULL	
	CONSTRAINT UQ_GuardLogin UNIQUE(GuardId, LoginDate, ClientSiteId)
)
GO

DROP TABLE GuardLogs
GO

CREATE TABLE [dbo].[GuardLogs]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ClientSiteLogBookId] INT NOT NULL FOREIGN KEY REFERENCES [ClientSiteLogBooks](Id) ON DELETE CASCADE,
	[EventDateTime] DATETIME NOT NULL,
	[Notes] VARCHAR(2048) NOT NULL,
	GuardLoginId INT NOT NULL FOREIGN KEY REFERENCES GuardLogins(Id)
)