CREATE TABLE dbo.ClientSitePatrolCars
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES dbo.ClientSites(Id) ON DELETE CASCADE,
	Model  VARCHAR(100) NOT NULL ,
	Rego VARCHAR(50) NOT NULL
)