CREATE TABLE [dbo].[UserClientSiteAccess]
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES ClientSites(Id)
)