CREATE TABLE dbo.KpiSendScheduleClientSites
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ScheduleId INT NOT NULL FOREIGN KEY REFERENCES KpiSendSchedules(Id) ON DELETE CASCADE,
	ClientSiteId INT NOT NULL FOREIGN KEY REFERENCES ClientSites(Id) ON DELETE CASCADE
)